### ISSUE TITLE
Initializing SortedSet with empty seq returns Set

### ISSUE THREAD

**Issue by DerGuteMoritz** [applitopia/immutable-sorted#2]
### What happened

The `SortedSet` constructor returns a `Set` rather than a `SortedSet` when called with an empty seq (as opposed to when called with a non-empty seq or `undefined`).

### How to reproduce

```js
> const { SortedSet, Seq } = require('immutable-sorted')
> SortedSet(Seq())
Set {}
```

**Comment by applitopia** [comment]
Thank you for reporting this bug. Fixed in v0.2.0.
