### ISSUE TITLE
Error when using `new` operator with SortedSet

### ISSUE THREAD

**Issue by abonander** [applitopia/immutable-sorted#3]
If one constructs a `SortedSet` with `new SortedSet()`, an error occurs, likely due to [this line](https://github.com/applitopia/immutable-sorted/blob/master/src/SortedSet.js#L26) since `this instanceof SortedSet` will return `true` but the inner map isn't initialized so it can't provide a comparator.  

It appears to be an Immutable.js convention to not use the `new` operator but the Immutable.js types also don't break when using the `new` operator so `SortedMap` and `SortedSet` shouldn't either. (`SortedMap` appears to not suffer from this problem, though.)

**Comment by applitopia** [comment]
Thank you for your fix, it has been merged and published to npm as immutable-sorted@0.2.5
